//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.RentDetails = new HashSet<RentDetail>();
        }
    
        public int ID { get; set; }
        public int CarID { get; set; }
        public Nullable<int> CarTypeID { get; set; }
        public double KM { get; set; }
        public string Image { get; set; }
        public bool IsDriveable { get; set; }
        public bool IsAvailable { get; set; }
        public int BranchID { get; set; }
    
        public virtual CarType CarType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentDetail> RentDetails { get; set; }
    }
}
